### ISSUE TITLE
Html support in messages

### ISSUE THREAD

**Issue by matyas-igor** [McNull/angular-inform#1]
Hi! 
I found your module very impressive, but it's a little bit pity that I cannot use html markdown in message content.
I suggest you to add html support simple adding this line in template:

```
<span ng-bind-html="msg.content"></span>
```

instead of just

```
{{ msg.content }}
```

And add html trusting in module:

```
        msg.content = $sce.trustAsHtml(content);
```

**Comment by McNull** [comment]
Hi,

I've added html support: http://plnkr.co/edit/x0sJj8?p=preview
